apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
     app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pdevopsacr.azurecr.io/backend:${tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080